# Generated by Django 5.1.2 on 2024-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Product Size'),
        ),
    ]
