# Generated by Django 5.0.6 on 2024-11-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
