# Generated by Django 5.0.6 on 2024-11-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shippingaddress_created_at_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
    ]
