# Generated by Django 5.0.6 on 2024-11-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
